"""Add referal system

Revision ID: 29b1600f9ca0
Revises: 8c878437cd43
Create Date: 2024-02-20 12:07:47.468604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29b1600f9ca0'
down_revision: Union[str, None] = '8c878437cd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('number', table_name='telephone_numbers')
    op.drop_table('telephone_numbers')
    op.add_column('users', sa.Column('referal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referal_id')
    op.create_table('telephone_numbers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='telephone_numbers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('number', 'telephone_numbers', ['number'], unique=True)
    # ### end Alembic commands ###
