"""Add language to User model

Revision ID: 9606ef1965e3
Revises: 29b1600f9ca0
Create Date: 2024-03-03 13:20:18.943696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9606ef1965e3'
down_revision: Union[str, None] = '29b1600f9ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.Enum('english', 'russian', 'german', 'arabic', 'chinese', 'polish', name='countriesenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
